version: "3"
services: 
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: postgres
      POSTGRES_DB: dheo
  app:
    image: dheo-product-expert
    ports:
      - 3000:3000